### ISSUE TITLE
Shooting sticky grenades inside a wall crashes the game

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-hover#55]
If you go up to a wall like seen in the video and shoot the sticky grenades, the game will crash.
If you're in a server, the host's game will crash and you will disconnect.
My guess is that they are trying to stick themselves to the back of the walls and that crashes the game. Quick fix would be to trace the player's aim and create a sticky where the ray hits.

https://user-images.githubusercontent.com/59583743/140428586-9c0fac00-90f2-43d0-9db1-4aac2db78f37.mp4

**Comment by kurozael** [comment]
Fixed in upcoming UI update.
