### ISSUE TITLE
"Exception has been thrown by the target of an invocation." and prediction error thrown during lag spikes softlocks you.

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-hover#57]
Whenever I and other players get a lag spike, the error "Exception has been thrown by the target of an invocation" appears you would get your mouse cursor to show up, meaning that moving your mouse and clicking won't do anything in game, basically softlocking you and forcing you to rejoin.
All we know so far is that it's not a problem tied with the host's fps and that it happened more frequently after the lag compensation update, so it might be related to prediction errors as they are thrown as well.

![connor](https://user-images.githubusercontent.com/59583743/140429607-e4d05503-9069-4516-a74c-d13c4268bfc6.png)

![cormac](https://user-images.githubusercontent.com/59583743/140429612-19005644-feb9-462c-89b1-8bd1653b784a.png)

**Comment by kurozael** [comment]
Doesn't happen anymore.
